name: main

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Create temporary output folder
        run: 'mkdir out'
      - name: Build source
        run: 'javac -d out Driver.java -verbose'
      - name: Build unit test suites
        run: 'javac -d out -cp "out:test/dependencies/junit-platform-console-standalone-1.8.2.jar"
              model/*UnitTest.java -verbose'
      - name: Run unit test suites
        run: 'java -jar test/dependencies/junit-platform-console-standalone-1.8.2.jar -cp out
              --scan-classpath --details=tree --fail-if-no-tests --reports-dir="test/reports"'
      - name: Publish test reports
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: 'test/reports/TEST-*.xml'
      - name: Run source
        run: 'java -cp out Driver ../test/data/dummy.csv'