name: main

on: [push]

jobs:
  build-test-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Setup JDK 17
        uses: actions/setup-java@v3.1.0
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Create temporary output folder
        run: 'mkdir out'
      - name: Build source
        run: 'javac -d out Driver.java -verbose'
      - name: Build unit tests
        run: 'javac -d test/unit-tests -cp "out:test/dependencies/junit-platform-console-standalone-1.8.2.jar"
              model/*UnitTest.java -verbose'
      - name: Run unit tests
        run: 'java -jar test/dependencies/junit-platform-console-standalone-1.8.2.jar -cp "out:test/unit-tests"
              --scan-classpath --details=tree --fail-if-no-tests --reports-dir="test/unit-tests/reports"'
      - name: Report unit test results
        uses: mikepenz/action-junit-report@v3.0.1
        if: always()
        with:
          report_paths: 'test/unit-tests/reports/TEST-*.xml'
          check_name: "report-unit-test-results"
      - name: Run Driver with dummy.csv
        run: 'java -cp out Driver ./test/data/dummy.csv'
  